spring:
  datasource:
    url: jdbc:h2:mem:bookstoredb
    driverClassName: org.h2.Driver
    username: sa
    password: skynet4ever
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"