version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: skynet
      POSTGRES_PASSWORD: skynet4ever
      PGPASSWORD: skynet4ever
    healthcheck:
      test: "pg_isready --username=skynet && psql --username=skynet --list"
      timeout: 10s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      # To keep data between restarts uncomment the next line
      # - ./postgres-data:/var/lib/postgresql/data

  #Liquibase container to initialize or update database.
  liquibase-update:
    container_name: liquibase
    image: liquibase/liquibase:4.20.0
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /db
    volumes:
      - ./db:/db
    command: --username=skynet --password=skynet4ever --url=jdbc:postgresql://postgres/bookstoredb --changeLogFile=changelog.xml --log-level=info update